---
- name: "Getting WordPress core files"
  include_tasks:
   file: core_file.yml

- name: "Modifying config"
  include_tasks: 
   file: modify_config.yml

- name: "database mngmt"
  include_tasks: 
   file: mysql_data.yml

- name: "wp-admin prompt input"
  include_tasks:
   file: prompt_input.yml
