---
- hosts: root_minions
  become: yes
        
  tasks:
   - name: "setting variable"
     ansible.builtin.setup:
      filter: 'ansible_mounts'
     register: mount_list

   - name: "handle mount"
     ansible.posix.mount:
      state: unmounted
      path: "{{ item.mount }}"
     loop: "{{ mount_list | json_query('ansible_facts.ansible_mounts[*]') }}"
     when: item.device  == '/dev/vdc'
   
