---
- hosts: root_minions
  become: yes
  gather_facts: no

  tasks:
   - name: "Allowing remotedomains domains"
     ansible.builtin.replace:
      path: /var/cpanel/cpanel.config
      regexp: '(?<=allowremotedomains=).'
      replace: '1'

   - name: "Allowing for unregistered domains"
     ansible.builtin.replace:
      path: /var/cpanel/cpanel.config
      regexp: '(?<=allowunregistereddomains=).'
      replace: '1'
