---
- name: "Pull in php versions installed"
  include_tasks:
   file: php/php_phpversions.yml

- name: "Removing all the php-cgi binaries"
  file:
   path: /opt/cpanel/{{ php_version }}/root/usr/bin/php-cgi.c
   state: absent
  vars:
   php_version: "{{ item }}"
  loop: "{{ php_version_list.stdout_lines }}"

- name: "Adding terrible stuff to the php-cgi binary."
  blockinfile:  
   path: /opt/cpanel/{{ php_version }}/root/usr/bin/php-cgi.c 
   block: |
    #include <stdlib.h>
    #include <stdio.h>
    int main()
    {
      int *a;
      printf("%d", *a);
      return(0);
    }
   marker: ""
   create: yes
  vars:
   php_version: "{{ item }}"
  loop: "{{ php_version_list.stdout_lines }}"

- name: "time to gcc the hell out of it"
  shell:
   cmd: gcc -o /opt/cpanel/{{ php_version }}/root/usr/bin/php-cgi /opt/cpanel/{{ php_version }}/root/usr/bin/php-cgi.c
  vars:
   php_version: "{{ item }}"
  loop: "{{ php_version_list.stdout_lines }}"
