---
- name: "Determine PHP Versions on the server."
  include_tasks:
   file: php/php_phpversions.yml
- name: "Change SAPI to none via cpanel tools"
  shell:
   cmd: /usr/local/cpanel/bin/rebuild_phpconf --{{ php_version }}=none
  vars:
   php_version: "{{ item }}"
  loop: "{{ php_version_list.stdout_lines }}"
