---
- name: "Create cPanel account using WHMAPI."
  shell: 
   cmd: whmapi1 createacct username={{ target_user }} domain={{ target_domain }} hasshell=1

- name: "Modify {{ target_user }} shell to /usr/local/cpanel/bin/jailshell"
  shell:
   cmd: whmapi1 modifyacct user={{ target_user }} shell=/usr/local/cpanel/bin/jailshell

- name: "Modify {{ target_user }} bashrc to fix umask issues HGT-3244"
  ansible.builtin.lineinfile:
   path: /home/{{ target_user }}/.bashrc
   line: 'umask 022'
   insertafter: EOF
   state: present
