---
# Setting variable to random password
- name: "Generating password and setting to variable"
  shell:
   cmd: echo "$(< /dev/urandom tr -dc _A-Z-a-z-0-9|head -c${1-24};)"
  register: wp_password

# Changeing the DB_PASSWORD in wp-config so it's incorrect
- name: "Setting DB_PASSWORD inside wp-config.php to be an incorrect password"
  replace:
   path: ~{{ target_user }}/public_html/wp-config.php
   regexp: 'define.+DB_PASSWORD.+;'
   replace: "define( 'DB_PASSWORD', '{{ wp_password.stdout }}' );"
# Changeing the DB_USER in wp-config so it's incorrect
- name: "Setting DB_USER inside wp-config.php to be an incorrect user"
  replace:
      path: ~{{ target_user }}/public_html/wp-config.php
      regexp: 'define.+DB_USER.+;'
      replace: "define( 'DB_USER', '{{ target_user }}_wp6' );"
