---
# modifying DNS zone's A record to cause cPanel suspended page.
- name: "Modiying DNS zone."
  replace:
   path: /var/named/{{ target_domain }}.db
   regexp: '{{ target_domain }}.+A.+(\d{1,3}\.){3}\d{1,3}'
   replace: "{{ target_domain }}. 14400 IN A 198.20.226.60"

#restarting named to ensure changes take effect.
- name: "Restart named service on box for changes to apply."
  service:
   name: pdns   
   state: restarted
